### ISSUE TITLE
Failed to build.

### ISSUE THREAD

**Issue by zwcloud** [nventive/Uno.Wasm.Bootstrap#30]
I haven't find the doc about how to build Uno.Wasm.Bootstrap. But I found a `build.ps1`, so tried to run it. But the result is
```text
PS D:\Workspace\1_Useful\Uno.Wasm.Bootstrap\build> D:\Workspace\1_Useful\Uno.Wasm.Bootstrap\build\build.ps1
Preparing to run build script...
Running build script...

========================================
Version
========================================
Cake.exe : An error occurred when executing task 'Version'.
At D:\Workspace\1_Useful\Uno.Wasm.Bootstrap\build\build.ps1:234 char:1
+ &$CAKE_EXE $cakeArguments
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (An error occurr...task 'Version'.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Error: 
One or more errors occurred.
	
GitVersion: Process returned an error (exit code 1).
```

**Comment by zwcloud** [comment]
When I tried to build Uno.Wasm.Bootstrap.sln in VS2017, the result is
```text
1>------ Build started: Project: Uno.Wasm.Bootstrap, Configuration: Debug Any CPU ------
1>C:\Users\cloud\.nuget\packages\microsoft.build.tasks.git\1.0.0-beta-62925-02\build\Microsoft.Build.Tasks.Git.targets(36,5): warning : Submodule 'src/Uno.Wasm.Bootstrap/linker' doesn't have any commit, the source code won't be available via source link.
1>LinkerSteps\ExplicitBlacklistStep.cs(24,12,24,17): error CS0234: The type or namespace name 'Cecil' does not exist in the namespace 'Mono' (are you missing an assembly reference?)
1>LinkerSteps\Extensions.cs(20,12,20,17): error CS0234: The type or namespace name 'Cecil' does not exist in the namespace 'Mono' (are you missing an assembly reference?)
1>LinkerSteps\PreserveTypeConverter.cs(32,12,32,17): error CS0234: The type or namespace name 'Cecil' does not exist in the namespace 'Mono' (are you missing an assembly reference?)
1>LinkerSteps\PreserveUsingAttributesStep.cs(20,12,20,17): error CS0234: The type or namespace name 'Cecil' does not exist in the namespace 'Mono' (are you missing an assembly reference?)
1>ShellTask.cs(28,12,28,17): error CS0234: The type or namespace name 'Cecil' does not exist in the namespace 'Mono' (are you missing an assembly reference?)
1>ShellTask.Linker.cs(28,12,28,17): error CS0234: The type or namespace name 'Cecil' does not exist in the namespace 'Mono' (are you missing an assembly reference?)
1>ShellTask.Linker.cs(29,12,29,17): error CS0234: The type or namespace name 'Cecil' does not exist in the namespace 'Mono' (are you missing an assembly reference?)
1>LinkerSteps\ExplicitBlacklistStep.cs(30,39,30,47): error CS0246: The type or namespace name 'BaseStep' could not be found (are you missing a using directive or an assembly reference?)
1>LinkerSteps\ExplicitBlacklistStep.cs(39,27,39,34): error CS0115: 'ExplicitBlacklistStep.Process()': no suitable method found to override
1>LinkerSteps\Extensions.cs(26,36,26,49): error CS0246: The type or namespace name 'TypeReference' could not be found (are you missing a using directive or an assembly reference?)
1>LinkerSteps\Extensions.cs(68,36,68,49): error CS0246: The type or namespace name 'TypeReference' could not be found (are you missing a using directive or an assembly reference?)
1>LinkerSteps\Extensions.cs(65,30,65,43): error CS0246: The type or namespace name 'TypeReference' could not be found (are you missing a using directive or an assembly reference?)
1>LinkerSteps\PreserveTypeConverter.cs(37,40,37,51): error CS0246: The type or namespace name 'ResolveStep' could not be found (are you missing a using directive or an assembly reference?)
1>LinkerSteps\PreserveUsingAttributesStep.cs(26,47,26,58): error CS0246: The type or namespace name 'ResolveStep' could not be found (are you missing a using directive or an assembly reference?)
1>LinkerSteps\PreserveTypeConverter.cs(54,30,54,44): error CS0246: The type or namespace name 'TypeDefinition' could not be found (are you missing a using directive or an assembly reference?)
1>LinkerSteps\PreserveUsingAttributesStep.cs(50,32,50,46): error CS0246: The type or namespace name 'TypeDefinition' could not be found (are you missing a using directive or an assembly reference?)
1>LinkerSteps\PreserveTypeConverter.cs(73,31,73,45): error CS0246: The type or namespace name 'TypeDefinition' could not be found (are you missing a using directive or an assembly reference?)
1>LinkerSteps\PreserveTypeConverter.cs(39,27,39,34): error CS0115: 'PreserveTypeConverters.Process()': no suitable method found to override
1>LinkerSteps\PreserveUsingAttributesStep.cs(70,31,70,45): error CS0246: The type or namespace name 'TypeDefinition' could not be found (are you missing a using directive or an assembly reference?)
1>LinkerSteps\PreserveUsingAttributesStep.cs(90,33,90,49): error CS0246: The type or namespace name 'MethodDefinition' could not be found (are you missing a using directive or an assembly reference?)
1>LinkerSteps\PreserveUsingAttributesStep.cs(95,27,95,41): error CS0246: The type or namespace name 'TypeDefinition' could not be found (are you missing a using directive or an assembly reference?)
1>LinkerSteps\PreserveUsingAttributesStep.cs(35,27,35,34): error CS0115: 'PreserveUsingAttributesStep.Process()': no suitable method found to override
1>ShellTask.cs(268,50,268,66): error CS0246: The type or namespace name 'EmbeddedResource' could not be found (are you missing a using directive or an assembly reference?)
1>ShellTask.cs(281,37,281,55): error CS0246: The type or namespace name 'AssemblyDefinition' could not be found (are you missing a using directive or an assembly reference?)
1>ShellTask.cs(281,64,281,80): error CS0246: The type or namespace name 'EmbeddedResource' could not be found (are you missing a using directive or an assembly reference?)
1>ShellTask.cs(298,11,298,27): error CS0246: The type or namespace name 'MethodDefinition' could not be found (are you missing a using directive or an assembly reference?)
1>ShellTask.Linker.cs(148,3,148,11): error CS0246: The type or namespace name 'Pipeline' could not be found (are you missing a using directive or an assembly reference?)
1>ShellTask.Linker.cs(165,24,165,31): error CS0246: The type or namespace name 'ILogger' could not be found (are you missing a using directive or an assembly reference?)
1>ShellTask.Linker.cs(171,27,171,44): error CS0246: The type or namespace name 'MessageImportance' could not be found (are you missing a using directive or an assembly reference?)
1>Done building project "Uno.Wasm.Bootstrap.csproj" -- FAILED.
```

**Comment by zwcloud** [comment]
No, there is no error when nuget restore:

```text
PS D:\Workspace\1_Useful\Uno.Wasm.Bootstrap\src\Uno.Wasm.Bootstrap> dotnet restore
  Restoring packages for D:\Workspace\1_Useful\Uno.Wasm.Bootstrap\src\Uno.Wasm.Bootstrap\Uno.Wasm.Bootstrap.csproj...
  Generating MSBuild file D:\Workspace\1_Useful\Uno.Wasm.Bootstrap\src\Uno.Wasm.Bootstrap\obj\Uno.Wasm.Bootstrap.csproj.nuget.g.props.
  Generating MSBuild file D:\Workspace\1_Useful\Uno.Wasm.Bootstrap\src\Uno.Wasm.Bootstrap\obj\Uno.Wasm.Bootstrap.csproj.nuget.g.targets.
  Restore completed in 941.09 ms for D:\Workspace\1_Useful\Uno.Wasm.Bootstrap\src\Uno.Wasm.Bootstrap\Uno.Wasm.Bootstrap.csproj.
```

**Comment by zwcloud** [comment]
No, there is no error when nuget restore:

```text
PS D:\Workspace\1_Useful\Uno.Wasm.Bootstrap\src\Uno.Wasm.Bootstrap> dotnet restore
  Restoring packages for D:\Workspace\1_Useful\Uno.Wasm.Bootstrap\src\Uno.Wasm.Bootstrap\Uno.Wasm.Bootstrap.csproj...
  Generating MSBuild file D:\Workspace\1_Useful\Uno.Wasm.Bootstrap\src\Uno.Wasm.Bootstrap\obj\Uno.Wasm.Bootstrap.csproj.nuget.g.props.
  Generating MSBuild file D:\Workspace\1_Useful\Uno.Wasm.Bootstrap\src\Uno.Wasm.Bootstrap\obj\Uno.Wasm.Bootstrap.csproj.nuget.g.targets.
  Restore completed in 941.09 ms for D:\Workspace\1_Useful\Uno.Wasm.Bootstrap\src\Uno.Wasm.Bootstrap\Uno.Wasm.Bootstrap.csproj.
```

**Comment by zwcloud** [comment]
OK. Now that #26 has been merged, I tried again to build the solution in VS2017. But before that, I got an error when update the submodule:
```text
git.exe submodule update --progress --init -- "src/Uno.Wasm.Bootstrap/linker"
error: pathspec 'src/Uno.Wasm.Bootstrap/linker' did not match any file(s) known to git.
```

**Comment by jeromelaban** [comment]
#35 will remove the use submodule, which is not used anymore. Also, for the restore, use visual studio's restore feature (or `msbuild /r`) instead of `dotnet restore`, as it's not supported yet by the projects in this solution.

**Comment by jeromelaban** [comment]
There, it should be better :) https://github.com/nventive/Uno.Wasm.Bootstrap/pull/35/files#diff-1e290ac8433d555bce009b162cb869d0R168

**Comment by zwcloud** [comment]
So fast!

**Comment by zwcloud** [comment]
new error when build Uno.Wasm.Sample:
```text
2>------ Rebuild All started: Project: Uno.Wasm.Sample, Configuration: Debug Any CPU ------
2>Uno.Wasm.Sample -> D:\Workspace\1_Useful\Uno.Wasm.Bootstrap\src\Uno.Wasm.Sample\bin\Debug\netstandard2.0\Uno.Wasm.Sample.dll
2>D:\Workspace\1_Useful\Uno.Wasm.Bootstrap\src\Uno.Wasm.Bootstrap\build\Uno.Wasm.Bootstrap.targets(57,3): error MSB4018: The "UnoInstallSDKTask_v0" task failed unexpectedly.
2>D:\Workspace\1_Useful\Uno.Wasm.Bootstrap\src\Uno.Wasm.Bootstrap\build\Uno.Wasm.Bootstrap.targets(57,3): error MSB4018: System.IO.InvalidDataException: Unable to find SHA in D:\Workspace\0_Experiment\MonoWasmDemo\MonoWasm
2>D:\Workspace\1_Useful\Uno.Wasm.Bootstrap\src\Uno.Wasm.Bootstrap\build\Uno.Wasm.Bootstrap.targets(57,3): error MSB4018:    at Uno.Wasm.Bootstrap.UnoInstallSDKTask_v0.InstallSdk()
2>D:\Workspace\1_Useful\Uno.Wasm.Bootstrap\src\Uno.Wasm.Bootstrap\build\Uno.Wasm.Bootstrap.targets(57,3): error MSB4018:    at Uno.Wasm.Bootstrap.UnoInstallSDKTask_v0.Execute()
2>D:\Workspace\1_Useful\Uno.Wasm.Bootstrap\src\Uno.Wasm.Bootstrap\build\Uno.Wasm.Bootstrap.targets(57,3): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
2>D:\Workspace\1_Useful\Uno.Wasm.Bootstrap\src\Uno.Wasm.Bootstrap\build\Uno.Wasm.Bootstrap.targets(57,3): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
2>Done building project "Uno.Wasm.Sample.csproj" -- FAILED.
```

**Comment by jeromelaban** [comment]
Can you show me the local path you used ?

**Comment by zwcloud** [comment]
```text
PS D:\Workspace\0_Experiment\MonoWasmDemo\MonoWasm> dir


    Directory: D:\Workspace\0_Experiment\MonoWasmDemo\MonoWasm


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       2018-11-29     22:17                dbg-proxy
d-----       2018-11-29     22:50                debug
d-----       2018-11-29     22:17                docs
d-----       2018-11-29     22:50                framework
d-----       2018-11-29     22:50                release
d-----       2018-11-29     22:17                wasm-bcl
-a----       2018-11-29     22:50          24687 bindings.cs
-a----       2018-11-29     22:50          31393 binding_support.js
-a----       2018-11-29     21:01            511 dependency.cs
-a----       2018-11-29     21:01           4068 dotnet_support.js
-a----       2018-11-29     22:50          15829 driver.c
-a----       2018-11-29     22:50        1408594 libmono-ee-interp.a
-a----       2018-11-29     22:50       16015076 libmono-icall-table.a
-a----       2018-11-29     22:50       16389732 libmono-ilgen.a
-a----       2018-11-29     22:50       20042180 libmonosgen-2.0.a
-a----       2018-11-29     21:01           7619 library_mono.js
-a----       2018-11-29     21:01         340992 Mono.Cecil.dll
-a----       2018-11-29     21:01          78336 Mono.WebAssembly.DebuggerProxy.dll
-a----       2018-11-29     21:01          16080 Mono.WebAssembly.DebuggerProxy.pdb
-a----       2018-11-29     21:01          56795 Options.cs
-a----       2018-11-29     22:50          66560 packager.exe
-a----       2018-11-29     21:01           3346 README.md
-a----       2018-11-29     21:01            263 runtime.js
-a----       2018-11-29     22:50           7873 sample.cs
-a----       2018-11-29     21:01           1834 sample.html
-a----       2018-11-29     21:01            726 server.py
-a----       2018-11-29     22:50          22849 WasmHttpMessageHandler.cs
```

**Comment by jeromelaban** [comment]
Ah got it. You have to provide the zip file's path to the bootstrapper, not an extracted folder.

**Comment by zwcloud** [comment]
Ah.. I will try it.

**Comment by zwcloud** [comment]
Great! It works finally!
![image](https://user-images.githubusercontent.com/6965758/49232798-a0032100-f42f-11e8-9bf9-9a0a3ffd7733.png)
